allow_network: false
firerunner_path: "firerunner"
kernel_path: "vmlinux-4.20.0"
runtimefs_dir: "./"
appfs_dir: "output/"
functions:
  start_assignment:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "start_assignment.img"
    concurrency_limit: 100
  gh_repo:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "gh_repo.img"
    concurrency_limit: 100
  go_grader:
    vcpus: 1
    memory: 256
    runtimefs: "python3.ext4"
    appfs: "go_grader.img"
    concurrency_limit: 100
  cos326_grader:
    vcpus: 1
    memory: 512
    runtimefs: "python3.ext4"
    appfs: "cos326_grader.img"
    concurrency_limit: 100
  cos326_parse_results:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "cos326_parse_results.img"
    concurrency_limit: 100
  cos326_parse_comment:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "cos326_parse_comment.img"
    concurrency_limit: 100
  grades:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "grades.img"
    concurrency_limit: 100
  generate_report:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "generate_report.img"
    concurrency_limit: 100
  post_comment:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "post_comment.img"
    concurrency_limit: 100
  cos326_find_ungraded:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "cos326_find_ungraded.img"
    concurrency_limit: 100
  cos326_find_not_submitted:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "cos326_find_not_submitted.img"
    concurrency_limit: 100
  cos326_grades:
    vcpus: 1
    memory: 128
    runtimefs: "python3.ext4"
    appfs: "cos326_grades.img"
    concurrency_limit: 100
